### ISSUE TITLE
could you help me figure it out, thanks.

### ISSUE THREAD

**Issue by liamxg** [mountainMath/BCCovidSnippets#1]
data %>% 
+     pivot_longer(c("Cases","Trend","Cleaned"),names_to="type",values_to="count")
Error in UseMethod("pivot_longer") : 
  no applicable method for 'pivot_longer' applied to an object of class "function"

**Comment by mountainMath** [comment]
That’s a function from the {tidyr} package. You need to install it or update to a newer version if you have an old one installed.

**Comment by liamxg** [comment]
data <- get_british_columbia_case_data() %>%
+     #filter(`Health Authority` %in% c("Vancouver Coastal","Fraser")) %>%
+     count(Date=`Reported Date`,name="Cases") %>%
+     filter(Date<max(Date),Date>=as.Date("2020-03-01")) %>%
+     mutate(Trend=extract_stl_trend_m(Cases),
+            Seasonal=extract_stl_seasonal_m(Cases)) %>%
+     mutate(Cleaned=Cases/Seasonal) %>%
+     cbind(compute_rolling_exp_fit(.$Trend))
Error in open.connection(con, "rb") : 
  Could not resolve host: www.bccdc.ca
> 
> label_y <- max(data$Cases) * 0.9
Error in data$Cases : object of type 'closure' is not subsettable

**Comment by liamxg** [comment]
I like your plot soooooo much, but can you help me figure it out, thanks.

**Comment by mountainMath** [comment]
Looks like your firewall is blocking http://www.bccdc.ca/?

**Comment by liamxg** [comment]
data_u <- get_british_columbia_hr_case_data() %>%
+     rename(HA=`Health Authority`,HR=`Health Region`) %>%
+     filter(HA != "Out of Canada") 
Error in open.connection(con, "rb") : 
  Could not resolve host: www.bccdc.ca

**Comment by liamxg** [comment]
i do not know why my firewall is blocking  www.bccdc.ca? i am in china now.

**Comment by mountainMath** [comment]
I don't know the particular reason bccdc is blocked for you, but China does frequently block websites of foreign government institutions and it's probably a good guess that this site is blocked from view in all of China. There is nothing particular about using BC data for this, if you are primarily interested in playing with the graph and the SLT decomposition you can swap out the BC data with whatever data source you have access to.

**Comment by liamxg** [comment]
thanks.
